### ISSUE TITLE
Amount and Vat not being picked on the invoice

### ISSUE THREAD

**Issue by pkawalya** [ricardovelero/invoicing-rails#16]
<img width="1164" alt="Screenshot 2024-01-05 at 09 15 42" src="https://github.com/ricardovelero/invoicing-rails/assets/1384372/d76d15c6-aba1-487a-ae45-0eb02fec45ab">

Thank you

**Comment by ricardovelero** [comment]
Hi Paul,
I can replicate the issue. I'll check the code and get back to you. Thanks!

**Comment by pkawalya** [comment]
Thank you

**Comment by ricardovelero** [comment]
Hi again,
I found the problem. I added English and Spanish locale to the app, and the locale query parameter was in the middle of the URL when the stimulus controller was fetching the item to calculate the VAT and item total. Also, it was happening when a client is selected. Now you should see the client's info when a client is selected. Please notice that the "Edit client" icon/link is not implemented yet. I think that would be my next fix, along with seriously considering using the locale as a URL path instead of a query parameter.

**Comment by ricardovelero** [comment]
Never mind, I found another problem with NaN showing in the total. I'm into it now.

**Comment by pkawalya** [comment]
Much appreciated. Thank you for the timely response

**Comment by pkawalya** [comment]
Thank you so much. Most appreciaed

**Comment by ricardovelero** [comment]
I've fixed the issues. Let me know if you find some other bug. Thanks.

**Comment by pkawalya** [comment]
Thank you. I will surely let you know as soon as I find any.

**Comment by pkawalya** [comment]
Thank you @ricardovelero. What are your thoughts on the alignment of the second item? 
<img width="1289" alt="Screenshot 2024-01-06 at 15 51 14" src="https://github.com/ricardovelero/invoicing-rails/assets/1384372/a1854e9e-e608-4ee4-b4e9-17afc4b157e1">

**Comment by ricardovelero** [comment]
Hi Paul,
That was one of the issues I fixed, looking at the calculation problem. You would need to update the code with those latest changes. 
<img width="1244" alt="Screenshot 2024-01-06 at 14 02 13" src="https://github.com/ricardovelero/invoicing-rails/assets/1290044/1e4af583-e0e6-40cf-8939-89d7ca1d854f">
