### ISSUE TITLE
undefined method `locale'  during onboarding

### ISSUE THREAD

**Issue by pkawalya** [ricardovelero/invoicing-rails#17]
undefined method `locale' for #<UserProfile id: 1, gov_id: "4554466466", street_address_1: "Kampala Uganda", street_address_2: "Kampala", city: "Kampala", region: "Kampala", postal_code: "00256", country: "UG", phone: nil, user_id: 1, created_at: "2024-01-06 18:27:38.262551000 +0300", updated_at: "2024-01-06 18:29:51.130577000 +0300", is_freelance: false, company_name: nil, first_name: "Paul", last_name: "Kawalya", email: nil>
<img width="1149" alt="Screenshot 2024-01-06 at 18 45 18" src="https://github.com/ricardovelero/invoicing-rails/assets/1384372/0e5ba6c9-d0ca-4991-96ef-7ea2fec01cbc">

**Comment by ricardovelero** [comment]
Hi Paul,
I think this is because you haven't run the latest migration on the database. Check the db/migrate/20231224164322_add_locale_to_user_profiles.rb to run the latest migration to add the locale to the db. After this, you can update the user profile page, which has the new "Preferences" tab to set your preferred language. In there, the next preference I will add is to choose your currency, but I haven't got into it yet.

**Comment by pkawalya** [comment]
True. Working well, thank you.
